# Generated by Django 3.0.6 on 2020-05-24 14:18

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogpost',
            managers=[
                ('Published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_image',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
